spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/Ruwan
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

server:
    port: 8081

jwt:
  auth:
    converter:
      resource-id: ruwan-rest-api
      principle-attributes : preferred_username


